// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://giiatkssfnntdtpcotyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpaWF0a3NzZm5udGR0cGNvdHlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzYyMzYsImV4cCI6MjA2MDk1MjIzNn0.sTwd3hTbXzdBEtIwmNQjcG_KDrE20P16efmWKMIjxvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);